# Generated by Django 4.2.4 on 2023-08-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MinimizerRetorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=100)),
                ('longName', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ActualInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('exerpt', models.CharField(max_length=500)),
                ('typeOfFact', models.CharField(max_length=100)),
                ('archiveLink', models.CharField(max_length=2000)),
                ('liveLink', models.CharField(max_length=2000)),
                ('categories', models.ManyToManyField(to='mainsite.infocategories')),
                ('retorts', models.ManyToManyField(to='mainsite.minimizerretorts')),
            ],
        ),
    ]
