# Generated by Django 4.2.4 on 2023-09-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(choices=[('LONG COVID EFFECTS ON BODY', 'Long covid & effects on the body'), ('LONG COVID ANECDOTES', 'Long covid anecdotes'), ('LONG COVID', 'Long covid'), ('MITIGATION AND EFFICACY', 'Mitigation and efficacy'), ('IMMUNE SYSTEM', 'Immune system'), ('ARTICLE', 'Article'), ('STUDY', 'Study'), ('ECONOMY', 'Economy'), ('TRANSMISSIBILITY', 'Transmission'), ('VACCINES', 'Vaccines'), ('Misc.', 'Misc')], default='Misc.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MinimizerRetorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=100)),
                ('longName', models.CharField(max_length=400)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActualInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ARTICLE STUDY', 'Article on a study'), ('ARTICLE OPINION', 'Opinion piece'), ('ARTICLE STATISTICS', 'Article on statistics'), ('ANECDOTE', 'Personal anecdote'), ('STUDY', 'Study'), ('STATISTICS', 'Statistics & Models'), ('EXAMPLE', 'Example'), ('OTHER/MIXED', 'Other / Mixed')], default='OTHER/MIXED', max_length=150)),
                ('source', models.CharField(choices=[('INDIVIDUAL ACCOUNT', 'Individual account'), ('MEDICAL PROFESSIONAL', 'Medical professional'), ('GROUP OF PROFESSIONALS', 'Group of professionals'), ('ENGINEER', 'Engineer'), ('GOVERNING BODY', 'Governing body'), ('OTHER/MIXED', 'Other / Mixed')], default='OTHER/MIXED', max_length=150)),
                ('archiveLink', models.CharField(max_length=2000, null=True)),
                ('liveLink', models.CharField(max_length=2000, null=True)),
                ('headline', models.CharField(max_length=500)),
                ('exerpt', models.CharField(max_length=500, null=True)),
                ('author', models.CharField(max_length=150, null=True)),
                ('authors_title', models.CharField(max_length=150, null=True)),
                ('participants', models.IntegerField(null=True)),
                ('datePublished', models.DateField(null=True)),
                ('dateArchived', models.DateField(null=True)),
                ('display', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='mainsite.infocategories')),
                ('retorts', models.ManyToManyField(to='mainsite.minimizerretorts')),
            ],
        ),
    ]
